version: "3"

services:
  user_db:
    image: postgres:12
    volumes:
      - user_mysql:/var/lib/postgresql/data
  user_web:
    build: .
    volumes:
      - .:/code
    ports:
      - "21700:21700"
    depends_on:
      - user_db

volumes:
  user_mysql:
