version: "3"

services:
  db:
    image: postgres:12
    volumes:
      - data:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "21700:21700"
    depends_on:
      - db

volumes:
  data:
