apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-web-container
  template:
    metadata:
      labels:
        app: user-web-container
    spec:
      containers:
        - name: user-web
          image: ashpx/user-web
          ports:
            - containerPort: 21700
          env:
            - name: DB_HOST
              value: postgres-service
          resources:
            requests:
              cpu: 100m

          volumeMounts:
            - name: postgres-volume-mount
              mountPath: /var/lib/busybox

          imagePullPolicy: Never

      volumes:
        - name: postgres-volume-mount
          persistentVolumeClaim:
            claimName: postgres-pvc
